name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run flake8
        run: flake8

      - name: Run pytest
        shell: bash
        run: |
          shopt -s nullglob globstar
          tests=(projects/**/tests/test_*.py tests/test_*.py)
          if [ ${#tests[@]} -gt 0 ]; then
            pytest
          else
            echo "No tests found. Skipping."
          fi
